apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timeseries-mqtt
spec:
  template:
    spec:
      containers:
        - name: timeseries-mqtt
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 512Mi