namespace: plantsuite

labels:
  - pairs:
      app: timeseries-mqtt
      app.kubernetes.io/name: timeseries-mqtt
    includeSelectors: true
    includeTemplates: true

resources:
  - hpa.yaml
  - virtualservice.yaml
  - pdb.yaml
  - service.yaml
  - statefulset.yaml

configMapGenerator:
  - name: timeseries-mqtt-appsettings
    files:
      - appsettings.json

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: plantsuite.azurecr.io/plantsuite-timeseries
    newTag: 0.16.0
