namespace: plantsuite

labels:
  - pairs:
      app: workflows
      app.kubernetes.io/name: workflows
    includeSelectors: true
    includeTemplates: true

resources:
  - deployment.yaml
  - virtualservice.yaml
  - service.yaml

configMapGenerator:
  - name: workflows-appsettings
    files:
      - appsettings.json
      - appsettings-ui.json

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: plantsuite.azurecr.io/plantsuite-workflows
    newTag: 1.2.2
  - name: plantsuite.azurecr.io/plantsuite-workflows-studio
    newTag: 1.2.2

