namespace: plantsuite

labels:
  - pairs:
      app: portal
      app.kubernetes.io/name: portal
    includeSelectors: true
    includeTemplates: true

resources:
  - deployment.yaml
  - hpa.yaml
  - virtualservice.yaml
  - pdb.yaml
  - service.yaml

configMapGenerator:
  - name: portal-appsettings
    envs:
      - appsettings.env

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: plantsuite.azurecr.io/plantsuite-iot-portal
    newTag: 0.45.0
