namespace: plantsuite

labels:
  - pairs:
      app: spc
      app.kubernetes.io/name: spc
    includeSelectors: true
    includeTemplates: true

resources:
  - deployment.yaml
  - hpa.yaml
  - virtualservice.yaml
  - pdb.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: spc-appsettings
    files:
      - appsettings.json

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: plantsuite.azurecr.io/plantsuite-spc
    newTag: 0.23.0
