namespace: plantsuite

labels:
  - pairs:
      app.kubernetes.io/part-of: plantsuite
    includeSelectors: true

resources:
  - namespace.yaml
  - ca-certificate-sync

secretGenerator:
  - name: plantsuite-env
    envs:
      - .env.secret
  - name: plantsuite-cr
    files:
      - .dockerconfigjson=dockerconfig.json
    type: kubernetes.io/dockerconfigjson
  - name: plantsuite-license
    files:
      - license.crt

generatorOptions:
  disableNameSuffixHash: true
