namespace: plantsuite

labels:
  - pairs:
      app: controlstations
      app.kubernetes.io/name: controlstations
    includeSelectors: true
    includeTemplates: true

resources:
  - deployment.yaml
  - hpa.yaml
  - virtualservice.yaml
  - pdb.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: controlstations-appsettings
    files:
      - appsettings.json

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: plantsuite.azurecr.io/plantsuite-controlstations
    newTag: 1.2.17