namespace: postgresql

resources:
  - plantsuite-ppgc.yaml

configMapGenerator:
  - name: plantsuite-ppgc-init-sql
    files:
      - init.sql

secretGenerator:
  - name: plantsuite-ppgc-pguser-postgres
    envs:
      - .env-postgres.secret
  - name: plantsuite-ppgc-pguser-keycloak
    envs:
      - .env-keycloak.secret
  - name: plantsuite-ppgc-pguser-vernemq
    envs:
      - .env-vernemq.secret

generatorOptions:
  disableNameSuffixHash: true
