#ref: https://github.com/percona/percona-postgresql-operator/blob/v2.8.2/deploy/cr.yaml
apiVersion: pgv2.percona.com/v2
kind: PerconaPGCluster
metadata:
  name: plantsuite-ppgc
  # annotations:
  #   pgv2.percona.com/authorizeBackupRemoval: "true"
spec:
  crVersion: 2.8.2

  users:
    - name: postgres
    - name: keycloak
      databases:
        - keycloak
    - name: vernemq
      databases:
        - vernemq

  databaseInitSQL:
    key: init.sql
    name: plantsuite-ppgc-init-sql

  image: docker.io/percona/percona-distribution-postgresql:17.7-2
  imagePullPolicy: IfNotPresent
  postgresVersion: 17
  instances:
    - name: ins1
      replicas: 3
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/data: postgres
                  postgres-operator.crunchydata.com/instance-set: ins1
              topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: 1000m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 1Gi
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

  proxy:
    pgBouncer:
      replicas: 3
      image: docker.io/percona/percona-pgbouncer:1.25.0-1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 128Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/role: pgbouncer
                topologyKey: kubernetes.io/hostname
      config:
        global:
          pool_mode: transaction
          default_pool_size: "30"
          min_pool_size: "10"
          max_db_connections: "200"

  backups:
    enabled: true
    pgbackrest:
      image: docker.io/percona/percona-pgbackrest:2.57.0-1
      containers:
        pgbackrest:
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 128Mi
        pgbackrestConfig:
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 128Mi
      configuration:
        - secret:
            name: s3
      global:
        repo1-retention-full: "8"
        repo1-retention-full-type: count
        repo1-retention-diff: "7"
        repo1-path: /pgbackrest/repo1
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          schedules:
            full: "30 1 * * 0" # semanalmente aos domingos às 01:30
            differential: "5 0 * * *" # diariamente às 00:05
            incremental: "20 1-23 * * *" # de hora em hora, exceto 00:20
          s3:
            bucket: pbm-postgresql
            endpoint: https://s3.us-southeast-1.amazonaws.com
            region: us-southeast-1

  pmm:
    enabled: false
    image: docker.io/percona/pmm-client:3.5.0
    secret: plantsuite-ppgc-pmm-secret
    serverHost: monitoring-service.pmm.svc.cluster.local
    resources:
      requests:
        memory: 256Mi
        cpu: 200m
      limits:
        memory: 256Mi
        cpu: 400m
