apiVersion: pgv2.percona.com/v2
kind: PerconaPGCluster
metadata:
  name: plantsuite-ppgc
spec:
  proxy:
    pgBouncer:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 100m
          memory: 256Mi
