apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis
subjects:
- kind: ServiceAccount
  name: redis
roleRef:
  kind: Role
  name: redis
  apiGroup: rbac.authorization.k8s.io