namespace: plantsuite

labels:
  - pairs:
      app: production
      app.kubernetes.io/name: production
    includeSelectors: true
    includeTemplates: true

resources:
  - deployment.yaml
  - rbac.yaml
  - hpa.yaml
  - virtualservice.yaml
  - pdb.yaml
  - service.yaml

configMapGenerator:
  - name: production-appsettings
    files:
      - appsettings.json

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: plantsuite.azurecr.io/production-api
    newTag: 0.3.0
