namespace: plantsuite

labels:
  - pairs:
      app: production
      app.kubernetes.io/name: production
    includeSelectors: true
    includeTemplates: true

resources:
  - deployment.yaml
  - hpa.yaml
  - virtualservice.yaml
  - pdb.yaml
  - service.yaml

configMapGenerator:
  - name: production-appsettings
    files:
      - appsettings.json

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: plantsuite.azurecr.io/plantsuite-production
    newTag: 2.0.0