apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plantsuite-wildcard
spec:
  secretName: plantsuite-wildcard-cert
  duration: 4380h        # 6 meses
  renewBefore: 720h      # 30 dias antes
  privateKey:
    algorithm: RSA
    size: 4096
  subject:
    organizations:
      - PlantSuite Software Ltda
    countries:
      - BR
    provinces:
      - SP
    localities:
      - Sao Paulo
  commonName: "*.plantsuite.local"
  dnsNames:
    - "*.plantsuite.local"
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
