namespace: plantsuite-mes

labels:
  - pairs:
      app.kubernetes.io/part-of: plantsuite-mes
    includeSelectors: true

resources:
  - controlstation
  - gateway
  - mes
  - namespace.yaml
  - production
  - sealedsecret-plantsuite-cr.yaml
  - wd

images:
  - name: plantsuite.azurecr.io/plantsuite-controlstations
    newTag: 1.2.17
  - name: plantsuite.azurecr.io/plantsuite-production
    newTag: 1.1.10
  - name: plantsuite.azurecr.io/plantsuite-mes
    newTag: 1.1.14
  - name: plantsuite.azurecr.io/plantsuite-gateway
    newTag: 1.1.7
  - name: plantsuite.azurecr.io/plantsuite-gateway-ui
    newTag: 1.1.7
  - name: plantsuite.azurecr.io/plantsuite-wd
    newTag: 1.0.0
  - name: plantsuite.azurecr.io/plantsuite-wd-ui
    newTag: 1.0.0