apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: plantsuite-rmq
spec:
  replicas: 3
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  persistence:
    storage: "50Gi"
