apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: valkey
subjects:
- kind: ServiceAccount
  name: valkey
roleRef:
  kind: Role
  name: valkey
  apiGroup: rbac.authorization.k8s.io