labels:
  - pairs:
      app: queries
      app.kubernetes.io/name: queries
    includeSelectors: true
    includeTemplates: true

resources:
  - deployment.yaml
  - hpa.yaml
  - virtualservice.yaml
  - pdb.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: queries-appsettings
    files:
      - appsettings.json

generatorOptions:
  disableNameSuffixHash: true
