namespace: plantsuite

labels:
  - pairs:
      app: tenants
      app.kubernetes.io/name: tenants
    includeSelectors: true
    includeTemplates: true

resources:
  - deployment.yaml
  - hpa.yaml
  - virtualservice.yaml
  - pdb.yaml
  - service.yaml

configMapGenerator:
  - name: tenants-appsettings
    files:
      - appsettings.json

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: plantsuite.azurecr.io/plantsuite-tenants
    newTag: 0.15.0
