apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: plantsuite-kc
spec:
  instances: 1
  db:
    # Ajustes para ambiente minimal, compatíveis com pgBouncer
    poolInitialSize: 5
    poolMinSize: 5
    poolMaxSize: 20