apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: plantsuite-kc-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: keycloak
      app.kubernetes.io/managed-by: keycloak-operator
      app.kubernetes.io/instance: plantsuite-kc
