#ref: https://github.com/percona/percona-server-mongodb-operator/blob/v1.22.0/deploy/cr.yaml
apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: plantsuite-psmdb
  finalizers:
    - percona.com/delete-psmdb-pods-in-order
spec:
  storageScaling:
    enableExternalAutoscaling: false
    enableVolumeScaling: true
    autoscaling:
      enabled: true
      triggerThresholdPercent: 80
      growthStep: 10Gi
      maxSize: "1000Gi"

  crVersion: 1.22.0
  image: percona/percona-server-mongodb:8.0.19-7
  imagePullPolicy: Always

  updateStrategy: SmartUpdate

  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
    schedule: "0 2 * * *"
    setFCV: false

  secrets:
    users: plantsuite-psmdb-secrets
    encryptionKey: plantsuite-psmdb-mongodb-encryption-key
    sse: plantsuite-psmdb-sse

  pmm:
    enabled: true
    image: percona/pmm-client:3.6.0
    serverHost: monitoring-service.pmm.svc.cluster.local
    mongodParams: --query-source=mongolog
    resources:
      requests:        
        cpu: 100m
        memory: 256Mi
      limits:        
        cpu: 300m
        memory: 256Mi

  replsets:
    - name: rs0
      size: 3
      tolerations:
        - key: dedicated
          operator: Equal
          value: mongo-rs
          effect: NoSchedule
      configuration: |
        setParameter:
          logLevel: 0
        operationProfiling:
          mode: off
          slowOpThresholdMs: 200
        systemLog:
          verbosity: 0
          destination: file
          path: /data/db/logs/mongod.log
          logAppend: true
          logRotate: rename
        storage:
          journal:
            enabled: true
      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"
      podDisruptionBudget:
        maxUnavailable: 1
      expose:
        enabled: false
        type: ClusterIP
      resources:
        requests:
          cpu: "1"
          memory: "16Gi"
        limits:
          cpu: "2"
          memory: "16Gi"
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 100Gi

  sharding:
    enabled: true
    configsvrReplSet:
      size: 3
      configuration: |
        setParameter:
          logLevel: 0
        operationProfiling:
          mode: off
          slowOpThresholdMs: 200
        systemLog:
          verbosity: 0
          destination: file
          path: /data/db/logs/mongod.log
          logAppend: true
          logRotate: rename
        storage:
          journal:
            enabled: true
      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"
      podDisruptionBudget:
        maxUnavailable: 1
      expose:
        enabled: false
        type: ClusterIP
      resources:
        requests:
          cpu: "300m"
          memory: "1Gi"
        limits:
          cpu: "600m"
          memory: "1Gi"
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 10Gi

    mongos:
      size: 3
      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        requests:
          cpu: "300m"
          memory: "1Gi"
        limits:
          cpu: "600m"
          memory: "1Gi"
      expose:
        type: ClusterIP

  backup:
    enabled: false
    image: percona/percona-backup-mongodb:2.12.0
    resources:
      requests:
        cpu: "100m"
        memory: "1Gi"
      limits:
        cpu: "600m"
        memory: "1Gi"
    storages:
      us-southeast-1:
        main: true
        type: s3
        s3:
          bucket: pbm-mongodb
          credentialsSecret: plantsuite-psmdb-backup-s3
          region: us-southeast-1
          endpointUrl: https://s3.us-southeast-1.amazonaws.com
          serverSideEncryption:
            sseCustomerAlgorithm: AES256
    pitr:
      enabled: true
      oplogOnly: false
      oplogSpanMin: 10
      compressionType: gzip
      compressionLevel: 6
    tasks:
      - name: daily-physical
        enabled: false
        schedule: "5 0 * * *" # diariamente às 00:05
        retention:
          count: 14
          type: count
          deleteFromStorage: true
        type: physical
        storageName: us-southeast-1
        compressionType: gzip
        compressionLevel: 6
      - name: daily-incremental-base
        enabled: false
        schedule: "5 0 * * *" # diariamente às 00:05
        retention:
          count: 14
          type: count
          deleteFromStorage: true
        type: incremental-base
        storageName: us-southeast-1
        compressionType: gzip
        compressionLevel: 6
      - name: hourly-incremental
        enabled: false
        schedule: "20 1-23 * * *" # de hora em hora, exceto 00:20
        type: incremental
        storageName: us-southeast-1
        compressionType: gzip
        compressionLevel: 6
      - name: weekly-physical
        enabled: false
        schedule: "30 1 * * 0" # semanalmente aos domingos às 01:30
        retention:
          count: 8
          type: count
          deleteFromStorage: true
        type: physical
        storageName: us-southeast-1
        compressionType: gzip
        compressionLevel: 6
      - name: monthly-physical
        enabled: false
        schedule: "45 2 1 * *" # mensalmente no dia 1 de cada mês às 02:45
        retention:
          count: 12
          type: count
          deleteFromStorage: true
        type: physical
        storageName: us-southeast-1
        compressionType: gzip
        compressionLevel: 6

  logcollector:
    enabled: true
    image: percona/fluentbit:4.0.1-2
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 256Mi
    logrotate:
      configuration: |
        /data/db/logs/mongod.full.log {
            daily
            maxsize 100M
            rotate 7
            missingok
            compress
            delaycompress
            notifempty
            copytruncate
            prerotate
                # rotate mongod.log using 'db.adminCommand({ logRotate: 1 })'
                mongosh "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/admin" \
                  --eval 'db.adminCommand({ logRotate: 1 })'
                find /data/db/logs/ -type f -name 'mongod.log.*' -delete
            endscript
        }
      extraConfig:
        name: logrotate-config
      schedule: "0 0 * * * *"
