namespace: plantsuite

labels:
  - pairs:
      app: alarms
      app.kubernetes.io/name: alarms
    includeSelectors: true
    includeTemplates: true

resources:
  - deployment.yaml
  - hpa.yaml
  - virtualservice.yaml
  - pdb.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: alarms-appsettings
    files:
      - appsettings.json

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: plantsuite.azurecr.io/plantsuite-alarms
    newTag: 0.6.0
