apiVersion: batch/v1
kind: Job
metadata:
  name: sync-ca-certificate-init
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: certificate-sync
      containers:
        - name: sync
          image: alpine/kubectl:1.34.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - /scripts/sync.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: scripts
          configMap:
            name: sync-ca-certificate-script
            defaultMode: 0755
      restartPolicy: Never
